name: diffusion_set_loss
focal_alpha: 0.25
focal_gamma: 2.0
class_weight: 2.0
l1_weight: 5.0
giou_weight: 2.0
deep_supervision: true

matcher:
  name: simota
  cost_class: 2.0
  cost_bbox: 5.0
  cost_giou: 2.0
  ota_k: 5
  center_radius: 2.5
